package com.nemo.api_health_monitor.mapper;

import com.nemo.api_health_monitor.domain.dto.EndpointResponseDto;
import com.nemo.api_health_monitor.domain.entity.Endpoint;

public class EndpointMapper {

    /**
     * Converts an API request (CreateBucketRequest) into a JPA entity (Bucket)
     * so we can save it to the database.
     *
     * Why only set 'name'?
     * - 'id' is auto-generated by @GeneratedValue(strategy = GenerationType.UUID)
     * - 'createdAt' is auto-set by @PrePersist
     * - 'objects' starts as an empty list, we don't set it here
     */
    public Bucket toEntity(CreateBucketRequest request) {
        return Bucket.builder()
                .name(request.name())   // Extract the name from the request record
                .build();               // Lombok @Builder generates this for us
    }

    /**
     * Converts a Bucket entity (from DB) into a BucketDto (for API response).
     * We also pass in objectCount separately because it's a computed value
     * (count of StorageObjects in this bucket), not stored directly on the entity.
     */
    public EndpointResponseDto toDto(Endpoint monitoredEndpoint) {
        return new EndpointResponseDto(
                monitoredEndpoint.getId(),
                monitoredEndpoint.getName(),
                monitoredEndpoint.getCreatedAt()
        );
    }
}
