package com.nemo.api_health_monitor.mapper;

import com.nemo.api_health_monitor.domain.dto.EndpointRequestDto;
import com.nemo.api_health_monitor.domain.dto.EndpointResponseDto;
import com.nemo.api_health_monitor.domain.entity.Endpoint;
import org.springframework.stereotype.Component;

import java.util.UUID;

@Component
public class EndpointMapper {

    /**
     * Converts an API request (EndpointRequestDto) into a JPA entity (Endpoint)
     * so we can save it to the database.
     *
     * Why only set 'name'?
     * - 'id' is auto-generated by @GeneratedValue(strategy = GenerationType.UUID)
     * - 'createdAt' is auto-set by @PrePersist
     * - 'objects' starts as an empty list, we don't set it here
     */
    public Endpoint toEntity(EndpointRequestDto request) {
        return Endpoint.builder()
                .name(request.name())   // Extract the name from the request record
                .build();               // Lombok @Builder generates this for us
    }

    /**
     * Converts a Bucket entity (from DB) into a BucketDto (for API response).
     * We also pass in objectCount separately because it's a computed value
     * (count of StorageObjects in this bucket), not stored directly on the entity.
     */
    public EndpointResponseDto toDto(Endpoint endpoint) {
        return new EndpointResponseDto(
                endpoint.getId(),
                endpoint.getName(),
                endpoint.getUrl(),
                endpoint.getMethod(),
                endpoint.getIntervalSeconds(),
                endpoint.getExpectedStatus(),
                endpoint.isActive(),
                endpoint.getCreatedAt()
        );
    }
}
